services:
  # a fully loaded development environment to test new code
  dev:
    &dev
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - BIBLIOTECA_BASE_PATH
    volumes:
      - ./:/code
      - ${BIBLIOTECA_BASE_PATH}:${BIBLIOTECA_BASE_PATH}

  # run all the tests
  test:
    <<: *dev
    command: pytest -v --cov=. --cov-report term-missing

  # run the linters
  # lint:
  #   <<: *dev
  #   <<: *mount-app-and-user-git-config
  #   entrypoint: docker/bump_version.sh
